services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/securevault
      - SECRET_KEY=supersecretkey
      - FERNET_KEY=vEjEB-_ubQxLGchyQLfOPDutwC0Avp-c3SJsqLvJRkk=
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=securevault
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: